/**
 * Circuit Detective — centralized bilingual string catalogue.
 * Every user-facing string lives here. Components never inline copy.
 */

export const en = {
  meta: {
    langName: "English",
    otherLangName: "العربية",
    switchLabel: "Switch language",
  },
  brand: {
    name: "Circuit Detective",
    volume: "notebook / vol.01",
  },
  nav: {
    caseFiles: "Case Files",
    notebook: "Notebook",
    certificate: "Certificate",
    about: "About",
    home: "Home",
    openMenu: "Open navigation menu",
    closeMenu: "Close navigation menu",
    menu: "Menu",
  },
  common: {
    engineer: "engineer",
    back: "Back",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    solved: "Solved",
    locked: "Locked",
    attempt: "attempt",
    attempts: "attempts",
    xp: "XP",
    accuracy: "accuracy",
    of: "of",
    notFound: "Case not found.",
    backToDesk: "back to the desk",
  },
  landing: {
    kicker: "volume 01 · investigation",
    h1a: "Learn to think",
    h1b: "like an engineer",
    lede:
      "Investigate failures, analyze evidence, and master systematic debugging through interactive engineering cases — one broken circuit at a time.",
    ctaPrimary: "Enter the case files",
    ctaSecondary: "or peek at the notebook →",
    marginNote:
      "\u201Cengineers don\u2019t memorize systems — they learn how systems break.\u201D",
    heroAlt:
      "Circuit workbench with breadboard, LED, resistor, battery and colorful wires",
    calloutPower: "power source",
    calloutSuspect: "the suspect",
    subjectSticker: "subject · board #001",
    readingTime: "t = 00:42",
    readingFault: "fault ●",
    detected: "detected",
    tags: [
      "● electronics debugging",
      "● robotics failure analysis",
      "● systematic thinking",
      "● hypothesis method",
      "● open source",
    ],
    philosophyKicker: "chapter 01 · the method",
    philosophyTitleA: "Three principles,",
    philosophyTitleB: "pinned above the bench.",
    philosophyNote:
      "\u201CWe don\u2019t teach circuits. We teach the questions engineers ask when a circuit refuses to work.\u201D",
    p1Sticker: "investigation",
    p1Title: "Investigation over memorization.",
    p1BodyA: "Learn how engineers ",
    p1Circled: "diagnose failures",
    p1BodyB: " instead of only studying systems when they work.",
    exhibitA: "exhibit A →",
    ledAlt: "Red LED component",
    p2Sticker: "scenario",
    p2Title: "Real engineering scenarios.",
    p2Body:
      "Practice troubleshooting inspired by real robotics and electronics challenges — the kind that fail minutes before a demo.",
    breadboardAlt: "Breadboard with jumper wires",
    p3Sticker: "notebook",
    p3Title: "An engineering notebook of your own.",
    p3Body:
      "Track discoveries, hypotheses, and debugging progress — the way real engineers do, in a book you can flip back through.",
    notebookEntryLabel: "entry / 03 · 42",
    notebookEntryLines: [
      "hypothesis: R7 open circuit",
      "measured: 3.3V at anode",
      "current: 0.00 mA — ✗",
    ],
    notebookEntryNext: "next: check solder joints",
    caseKicker: "chapter 02 · the first case",
    caseTitle: "Case File",
    caseNote:
      "\u201Cclipped to the desk this morning — still warm from the printer.\u201D",
    classified: "classified · locked",
    incidentReport: "incident report · robotics lab",
    case001Title: "The Silent LED.",
    case001BodyA:
      "Minutes before a robotics competition, the robot indicator LED stops working. Voltage is present. Current is not. ",
    case001Highlight: "Find the failure.",
    difficulty: "difficulty",
    category: "category",
    estTime: "est. time",
    status: "status",
    beginner: "Beginner",
    electronics: "Electronics",
    time18: "~ 18 min",
    openCase001: "Open case #001 →",
    seeAllFiles: "see all files →",
    evidencePinned: "evidence · pinned",
    items03: "03 items",
    ev: {
      battery: { name: "9V Battery", meta: "PWR · Vin", note: "reads 9.02 V", status: "OK" },
      resistor: { name: "Resistor · 220Ω", meta: "R7 · 1/4W", note: "untested — start here", status: "?" },
      led: { name: "Indicator LED", meta: "D3 · red 5mm", note: "3.3V present · no current", status: "FAIL" },
    },
    quote:
      "\u201Cthe multimeter is honest. the circuit is lying. somewhere between the two — the answer.\u201D",
    footerBlurb:
      "An engineering education project — a beautiful notebook for curious students who\u2019d rather take things apart than take notes.",
    createdBy: "— created by",
    explore: "explore",
    colophon: "colophon",
    colophonBody: "Set in Instrument Serif, Caveat, and JetBrains Mono.",
    rights: "© 2026 · circuit_detective",
    soldered: "soldered with care",
  },
  hub: {
    kicker: "chapter 02 · the desk",
    title: "Case files,",
    note:
      "\u201Cfive sealed folders on the desk. one is open. the rest unlock as you prove yourself.\u201D",
    statSolved: "solved",
    statXp: "total xp",
    statAccuracy: "accuracy",
    claimCertificate: "Claim certificate",
    signedInAs: "signed in as",
    resetProfile: "reset profile",
    metaTitle: "Case Investigation Hub — Circuit Detective",
    metaDesc:
      "Choose an engineering case to investigate. Diagnose faults, form hypotheses, unlock progressive cases.",
  },
  caseCard: {
    caseFile: "case file",
    open: "open the file →",
  },
  investigation: {
    backToDesk: "back to desk",
    incident: "incident report · case",
    evidenceWorkbench: "evidence · workbench",
    inspected: "inspected",
    probeHint: "\u201Cclick each component to probe it with the multimeter.\u201D",
    diagnosisPanel: "diagnosis panel",
    gatherMore:
      "gather more evidence — probe at least {n} components before submitting a diagnosis.",
    selectFault: "Based on your measurements, select the most likely fault:",
    keepGoing: "keep going, engineer",
    notMatchingYet: "That hypothesis doesn\u2019t match the evidence yet.",
    reExamine: "re-examine evidence",
    caseSolved: "case solved",
    xpLogged: "+{xp} XP logged into your notebook.",
    submit: "Submit engineering diagnosis",
    physics: "the physics",
    whyTitle: "Why this failure happens.",
    conceptsMastered: "concepts mastered",
    reflectionLabel: "your reflection · notebook",
    reflectionPlaceholder:
      "what did you notice? what will you check first next time?",
    saveReflection: "save reflection",
    nextCase: "Next case:",
    claimCertificate: "Claim your certificate →",
  },
  multimeter: {
    header: "multimeter · dmm-01",
    live: "● live",
    idle: "— — —",
    scanning: "scanning…",
    probePrompt: "probe a component",
    noSignal: "no signal",
  },
  notebook: {
    kicker: "chapter 03 · the notebook",
    titleOwner: "\u2019s ",
    title: "engineering notebook",
    note:
      "\u201Cevery solved case, every hypothesis — pressed between these pages.\u201D",
    statCases: "cases solved",
    statXp: "total xp",
    statAccuracy: "accuracy",
    statEngineer: "engineer",
    empty:
      "\u201Cthe notebook is still blank — solve a case to write your first entry.\u201D",
    entry: "entry · case",
    fault: "fault",
    concepts: "concepts mastered",
    reflection: "reflection",
    addReflection: "— add a reflection —",
    reflectionPlaceholder: "what did you learn?",
    metaTitle: "Engineering Notebook — Circuit Detective",
    metaDesc:
      "Your handwritten record of solved cases, reflections, and concepts mastered.",
  },
  certificate: {
    kicker: "chapter 04 · the recognition",
    titleA: "Certificate of",
    titleB: "accomplishment",
    allSolved: "all five cases solved",
    earned: "You\u2019ve earned it,",
    printNote: "\u201Cprint it. frame it. or tape it above your bench.\u201D",
    view: "View & print certificate",
    lockedCount: "cases solved",
    notYet: "Not yet, engineer.",
    lockedNote:
      "\u201Cthe certificate unlocks when all five case files are closed.\u201D",
    backToDesk: "Back to the desk →",
    print: "Print / Save as PDF",
    copy: "Copy achievement summary",
    copied: "Copied",
    vol: "circuit detective · vol.01",
    heading1: "Certificate of",
    heading2: "Engineering Accomplishment",
    confirms: "this notebook confirms that",
    anonymous: "Anonymous Engineer",
    ofTeam: "of",
    body:
      "has systematically investigated and diagnosed all five engineering failure cases — demonstrating patience, rigor, and the willingness to trust the multimeter over the assumption.",
    statCases: "cases solved",
    statXp: "total xp",
    statAccuracy: "accuracy",
    statAwarded: "awarded",
    skills: "skills mastered",
    idLabel: "certificate id",
    signature: "— Circuit Detective",
    signedWith: "a local completion record · not an accredited credential",
    metaTitle: "Certificate of Engineering Accomplishment — Circuit Detective",
    metaDesc:
      "Your printable certificate awarded for solving all five Circuit Detective cases.",
  },
  onboarding: {
    kicker: "enroll · engineer profile",
    title: "Welcome to the lab.",
    note: "\u201Cbefore we open a case file, tell us who\u2019s investigating.\u201D",
    nameLabel: "engineer name",
    namePlaceholder: "Ada Lovelace",
    levelLabel: "experience level",
    ageLabel: "age group",
    teamLabel: "school or robotics team",
    optional: "(optional)",
    teamPlaceholder: "Team Sparkfire · Robotics Club",
    errorEmpty: "Please enter your engineer name.",
    errorLong: "Name is a bit long — 40 chars max.",
    submit: "Open my case files →",
    levels: {
      Beginner: "Beginner",
      "Electronics Explorer": "Electronics Explorer",
      "Robotics Builder": "Robotics Builder",
    },
  },
} as const;

/** Widen literal types so translations aren't forced to equal the English text. */
type Widen<T> = T extends string
  ? string
  : T extends readonly (infer U)[]
    ? readonly Widen<U>[]
    : { -readonly [K in keyof T]: Widen<T[K]> };

export type Dict = Widen<typeof en>;

export const ar: Dict = {
  meta: {
    langName: "العربية",
    otherLangName: "English",
    switchLabel: "تغيير اللغة",
  },
  brand: {
    name: "المحقّق الكهربائي",
    volume: "دفتر المختبر / المجلد ٠١",
  },
  nav: {
    caseFiles: "ملفات القضايا",
    notebook: "دفتر الهندسة",
    certificate: "الشهادة",
    about: "عن المشروع",
    home: "الرئيسية",
    openMenu: "فتح قائمة التنقل",
    closeMenu: "إغلاق قائمة التنقل",
    menu: "القائمة",
  },
  common: {
    engineer: "مهندس",
    back: "رجوع",
    close: "إغلاق",
    save: "حفظ",
    cancel: "إلغاء",
    solved: "تم حلها",
    locked: "مقفلة",
    attempt: "محاولة",
    attempts: "محاولات",
    xp: "نقطة",
    accuracy: "الدقة",
    of: "من",
    notFound: "لم يتم العثور على القضية.",
    backToDesk: "العودة إلى الطاولة",
  },
  landing: {
    kicker: "المجلد ٠١ · التحقيق",
    h1a: "تعلّم أن تفكّر",
    h1b: "مثل المهندسين",
    lede:
      "حقّق في الأعطال، وحلّل الأدلة، وأتقن التشخيص المنهجي عبر قضايا هندسية تفاعلية — دائرة معطّلة واحدة في كل مرة.",
    ctaPrimary: "ادخل إلى ملفات القضايا",
    ctaSecondary: "أو ألقِ نظرة على الدفتر ←",
    marginNote: "«المهندس لا يحفظ الأنظمة — بل يتعلّم كيف تتعطّل.»",
    heroAlt: "طاولة عمل إلكترونية عليها لوحة تجارب ومصباح LED ومقاومة وبطارية وأسلاك ملوّنة",
    calloutPower: "مصدر الطاقة",
    calloutSuspect: "المُشتبه به",
    subjectSticker: "العيّنة · لوحة رقم ٠٠١",
    readingTime: "الزمن = ٠٠:٤٢",
    readingFault: "عطل ●",
    detected: "مُكتشف",
    tags: [
      "● تشخيص الإلكترونيات",
      "● تحليل أعطال الروبوتات",
      "● التفكير المنهجي",
      "● منهج الفرضيات",
      "● مفتوح المصدر",
    ],
    philosophyKicker: "الفصل ٠١ · المنهج",
    philosophyTitleA: "ثلاثة مبادئ،",
    philosophyTitleB: "معلّقة فوق طاولة العمل.",
    philosophyNote:
      "«نحن لا نُدرّس الدوائر. نحن نُدرّس الأسئلة التي يطرحها المهندس حين ترفض الدائرة أن تعمل.»",
    p1Sticker: "التحقيق",
    p1Title: "التحقيق قبل الحفظ.",
    p1BodyA: "تعلّم كيف يقوم المهندسون بـ",
    p1Circled: "تشخيص الأعطال",
    p1BodyB: " بدلاً من دراسة الأنظمة وهي تعمل فقط.",
    exhibitA: "الدليل الأول ←",
    ledAlt: "مصباح LED أحمر",
    p2Sticker: "السيناريو",
    p2Title: "سيناريوهات هندسية واقعية.",
    p2Body:
      "تدرّب على حلّ المشكلات المستوحاة من تحديات حقيقية في الروبوتات والإلكترونيات — من النوع الذي يتعطّل قبل العرض بدقائق.",
    breadboardAlt: "لوحة تجارب مع أسلاك توصيل",
    p3Sticker: "الدفتر",
    p3Title: "دفتر هندسي خاص بك.",
    p3Body:
      "سجّل الاكتشافات والفرضيات وتقدّم التشخيص — تمامًا كما يفعل المهندسون، في دفتر يمكنك العودة إليه.",
    notebookEntryLabel: "قيد / ٠٣ · ٤٢",
    notebookEntryLines: [
      "الفرضية: المقاومة R7 مفتوحة",
      "القياس: ٣٫٣ فولت عند الأنود",
      "التيار: ٠٫٠٠ مللي أمبير — ✗",
    ],
    notebookEntryNext: "التالي: افحص نقاط اللحام",
    caseKicker: "الفصل ٠٢ · القضية الأولى",
    caseTitle: "ملف القضية",
    caseNote: "«وصل إلى الطاولة هذا الصباح — ما زال دافئًا من الطابعة.»",
    classified: "سرّي · مقفل",
    incidentReport: "تقرير حادثة · مختبر الروبوتات",
    case001Title: "المصباح الصامت.",
    case001BodyA:
      "قبل دقائق من مسابقة الروبوتات، يتوقف مصباح المؤشّر عن العمل. الجهد موجود. التيار غائب. ",
    case001Highlight: "اعثر على العطل.",
    difficulty: "المستوى",
    category: "التصنيف",
    estTime: "الوقت المتوقع",
    status: "الحالة",
    beginner: "مبتدئ",
    electronics: "إلكترونيات",
    time18: "≈ ١٨ دقيقة",
    openCase001: "افتح القضية ٠٠١ ←",
    seeAllFiles: "عرض كل الملفات ←",
    evidencePinned: "الأدلة · مثبّتة",
    items03: "٣ عناصر",
    ev: {
      battery: { name: "بطارية ٩ فولت", meta: "الطاقة · الدخل", note: "القراءة ٩٫٠٢ فولت", status: "سليم" },
      resistor: { name: "مقاومة · ٢٢٠ أوم", meta: "R7 · ربع واط", note: "لم تُفحص — ابدأ من هنا", status: "؟" },
      led: { name: "مصباح المؤشّر", meta: "D3 · أحمر ٥ مم", note: "٣٫٣ فولت موجود · لا تيار", status: "عطل" },
    },
    quote: "«جهاز القياس صادق. الدائرة تكذب. بينهما — تكمن الإجابة.»",
    footerBlurb:
      "مشروع تعليمي هندسي — دفتر أنيق للطلاب الفضوليين الذين يفضّلون تفكيك الأشياء على تدوين الملاحظات.",
    createdBy: "— من إعداد",
    explore: "استكشف",
    colophon: "الخطوط",
    colophonBody: "مصفوف بخطوط Instrument Serif وCaveat وJetBrains Mono.",
    rights: "© ٢٠٢٦ · المحقّق الكهربائي",
    soldered: "صُنع بعناية",
  },
  hub: {
    kicker: "الفصل ٠٢ · الطاولة",
    title: "ملفات القضايا،",
    note: "«خمسة ملفات مغلقة على الطاولة. واحد مفتوح. والبقية تُفتح كلما أثبتّ جدارتك.»",
    statSolved: "المحلولة",
    statXp: "مجموع النقاط",
    statAccuracy: "الدقة",
    claimCertificate: "استلم الشهادة",
    signedInAs: "الدخول باسم",
    resetProfile: "إعادة ضبط الملف",
    metaTitle: "مركز التحقيقات — المحقّق الكهربائي",
    metaDesc: "اختر قضية هندسية للتحقيق فيها: شخّص الأعطال، وكوّن الفرضيات، وافتح قضايا جديدة.",
  },
  caseCard: {
    caseFile: "ملف قضية",
    open: "افتح الملف ←",
  },
  investigation: {
    backToDesk: "العودة إلى الطاولة",
    incident: "تقرير حادثة · قضية",
    evidenceWorkbench: "الأدلة · طاولة العمل",
    inspected: "تم فحصها",
    probeHint: "«اضغط على كل مكوّن لقياسه بجهاز الملتيميتر.»",
    diagnosisPanel: "لوحة التشخيص",
    gatherMore: "اجمع المزيد من الأدلة — افحص {n} مكوّنات على الأقل قبل تقديم التشخيص.",
    selectFault: "بناءً على قياساتك، اختر العطل الأرجح:",
    keepGoing: "واصل التفكير، أيها المهندس",
    notMatchingYet: "هذه الفرضية لا تتوافق مع الأدلة بعد.",
    reExamine: "أعد فحص الأدلة",
    caseSolved: "تم حلّ القضية",
    xpLogged: "أُضيفت {xp} نقطة إلى دفترك.",
    submit: "قدّم التشخيص الهندسي",
    physics: "الفيزياء وراء العطل",
    whyTitle: "لماذا يحدث هذا العطل.",
    conceptsMastered: "المفاهيم المُتقنة",
    reflectionLabel: "تأمّلك · الدفتر",
    reflectionPlaceholder: "ماذا لاحظت؟ وما أول شيء ستفحصه في المرة القادمة؟",
    saveReflection: "حفظ التأمّل",
    nextCase: "القضية التالية:",
    claimCertificate: "استلم شهادتك ←",
  },
  multimeter: {
    header: "ملتيميتر · DMM-01",
    live: "● مباشر",
    idle: "— — —",
    scanning: "جارٍ القياس…",
    probePrompt: "اختر مكوّنًا للقياس",
    noSignal: "لا إشارة",
  },
  notebook: {
    kicker: "الفصل ٠٣ · الدفتر",
    titleOwner: " ",
    title: "دفتر الهندسة",
    note: "«كل قضية مُغلقة، وكل فرضية — محفوظة بين هذه الصفحات.»",
    statCases: "القضايا المحلولة",
    statXp: "مجموع النقاط",
    statAccuracy: "الدقة",
    statEngineer: "المهندس",
    empty: "«الدفتر ما زال فارغًا — حلّ قضية لتكتب أول قيد.»",
    entry: "قيد · قضية",
    fault: "العطل",
    concepts: "المفاهيم المُتقنة",
    reflection: "التأمّل",
    addReflection: "— أضف تأمّلًا —",
    reflectionPlaceholder: "ماذا تعلّمت؟",
    metaTitle: "دفتر الهندسة — المحقّق الكهربائي",
    metaDesc: "سجلّك الخاص بالقضايا المحلولة والتأمّلات والمفاهيم المُتقنة.",
  },
  certificate: {
    kicker: "الفصل ٠٤ · التقدير",
    titleA: "شهادة",
    titleB: "إنجاز هندسي",
    allSolved: "تم حلّ القضايا الخمس",
    earned: "لقد استحققتها،",
    printNote: "«اطبعها. أطّرها. أو علّقها فوق طاولتك.»",
    view: "عرض الشهادة وطباعتها",
    lockedCount: "قضية محلولة",
    notYet: "ليس بعد، أيها المهندس.",
    lockedNote: "«تُفتح الشهادة عند إغلاق ملفات القضايا الخمس.»",
    backToDesk: "العودة إلى الطاولة ←",
    print: "طباعة / حفظ PDF",
    copy: "نسخ ملخّص الإنجاز",
    copied: "تم النسخ",
    vol: "المحقّق الكهربائي · المجلد ٠١",
    heading1: "شهادة",
    heading2: "إنجاز هندسي",
    confirms: "يؤكّد هذا الدفتر أنّ",
    anonymous: "مهندس مجهول",
    ofTeam: "من",
    body:
      "قد حقّق وشخّص بشكل منهجي جميع قضايا الأعطال الهندسية الخمس — مُظهرًا صبرًا ودقّة واستعدادًا للثقة بالقياس بدلًا من الافتراض.",
    statCases: "القضايا المحلولة",
    statXp: "مجموع النقاط",
    statAccuracy: "الدقة",
    statAwarded: "تاريخ المنح",
    skills: "المهارات المُتقنة",
    idLabel: "رقم الشهادة",
    signature: "— المحقّق الكهربائي",
    signedWith: "سجلّ إتمام محلي · وليس شهادة معتمدة",
    metaTitle: "شهادة إنجاز هندسي — المحقّق الكهربائي",
    metaDesc: "شهادتك القابلة للطباعة بعد حلّ قضايا المحقّق الكهربائي الخمس.",
  },
  onboarding: {
    kicker: "التسجيل · ملف المهندس",
    title: "أهلًا بك في المختبر.",
    note: "«قبل أن نفتح ملف القضية، أخبرنا من المحقّق.»",
    nameLabel: "اسم المهندس",
    namePlaceholder: "آدا لوفليس",
    levelLabel: "مستوى الخبرة",
    ageLabel: "الفئة العمرية",
    teamLabel: "المدرسة أو فريق الروبوتات",
    optional: "(اختياري)",
    teamPlaceholder: "فريق الشرارة · نادي الروبوتات",
    errorEmpty: "من فضلك أدخل اسم المهندس.",
    errorLong: "الاسم طويل قليلًا — ٤٠ حرفًا كحد أقصى.",
    submit: "افتح ملفات قضاياي ←",
    levels: {
      Beginner: "مبتدئ",
      "Electronics Explorer": "مستكشف إلكترونيات",
      "Robotics Builder": "باني روبوتات",
    },
  },
};

export const dictionaries = { en, ar } as const;
export type Lang = keyof typeof dictionaries;
