/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as HubRouteImport } from './routes/hub'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseIdRouteImport } from './routes/case.$id'

const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIdRoute = CaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/hub': typeof HubRoute
  '/notebook': typeof NotebookRoute
  '/case/$id': typeof CaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/hub': typeof HubRoute
  '/notebook': typeof NotebookRoute
  '/case/$id': typeof CaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/hub': typeof HubRoute
  '/notebook': typeof NotebookRoute
  '/case/$id': typeof CaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificate' | '/hub' | '/notebook' | '/case/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificate' | '/hub' | '/notebook' | '/case/$id'
  id: '__root__' | '/' | '/certificate' | '/hub' | '/notebook' | '/case/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  HubRoute: typeof HubRoute
  NotebookRoute: typeof NotebookRoute
  CaseIdRoute: typeof CaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$id': {
      id: '/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof CaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  HubRoute: HubRoute,
  NotebookRoute: NotebookRoute,
  CaseIdRoute: CaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
